version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: resume-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: resume_db
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - resume-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  resume-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-builder-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      # MongoDB Configuration
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@mongodb:27017/resume_db?authSource=admin
      SPRING_DATA_MONGODB_DATABASE: resume_db
      
      # JWT Configuration
      JWT_SECRET: Y29tcGxleF9zZWNyZXRfa2V5X2Zvcl9yZXN1bWVfYnVpbGRlcl9hcGlfMjAyNQ==
      JWT_EXPIRATION: 86400000
      
      # Application Configuration
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8080
      
      # Logging
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_ZIDIO_TASK: DEBUG
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - resume-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  resume-network:
    driver: bridge
