spring:
  application:
    name: resume-builder-api
  
  # MongoDB Configuration - Use environment variable for production
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/resume_db}
      database: ${SPRING_DATA_MONGODB_DATABASE:resume_db}
      auto-index-creation: true
  
  # Server Configuration
  servlet:
    context-path: /
  
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

# Server Configuration - Use PORT environment variable for Render
server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  
  # Error Configuration
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentOnlyPleaseChangeInProduction}
  expiration: ${JWT_EXPIRATION:86400000}

# Logging Configuration
logging:
  level:
    root: INFO
    com.zidio_task.resume: INFO
    org.springframework.web: INFO
    org.springframework.data.mongodb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# SpringDoc Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tags-sorter: alpha
  show-actuator: false

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

# Application Info
info:
  app:
    name: Resume Builder API
    description: RESTful API for managing resumes
    version: 1.0.0
    developer: Darshan Sudhakar Jadhav
    company: Zidio Development
